### ISSUE TITLE
Ubuntu 22.04 - Syncthingy Wont Stay running

### ISSUE THREAD

**Issue by trymeouteh** [zocker-160/SyncThingy#12]
I have changed the permissions and even clicked the Reset button in Flatseal. No matter what I do, when I launch Syncthingy, it will run for about 30 seconds to a minute, never connects to another device and then Syncthing and Syncthingy will shutdown.

```
$ flatpak run com.github.zocker_160.SyncThingy
Gtk-Message: 13:21:19.106: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:21:19.106: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
running inside Flatpak 

Using Icon: "com.github.zocker_160.SyncThingy"
/app/bin/syncthing
Requesting background permission...
Background / Autostart permission revoked
```

**Comment by zocker-160** [comment]
Yes because the Flatpak does not have the permission to run in the background, which causes the application to be killed by the system after a minute or so.

It says it in the logs:
> Background / Autostart permission revoked

In order to make this work, you need a working background portal, which on Ubuntu is part of the `xdg-desktop-portal` and `xdg-desktop-portal-kde` or `xdg-desktop-portal-gtk` packages.

Those need to be installed and running.

**Comment by zocker-160** [comment]
nice, glad to hear!

**Comment by CestQuoiUnPseudo** [comment]
Same problem, installed from the Pop!_Shop, would run for a minute then stop.
Changing permission (Portals -> Background) in Flatseal fixed it!
Thanks for the program @zocker-160!

**Comment by zocker-160** [comment]
Yeah I sadly do not know why this happens, usually when running the application for the first time, the background portal should show a popup message asking the user to grant the permission to run in the background.
