### ISSUE TITLE
SyncThingy doesn't start when already running as a service

### ISSUE THREAD

**Issue by mrexodia** [zocker-160/SyncThingy#13]
Setup: https://dev.to/mrexodia/ffxiv-cloud-saves-on-steam-deck-24k5#syncthing-as-a-service-on-the-steam-deck

This works great and runs Syncthing also in gaming mode (loosely related to #11 I guess). Unfortunately when launching the 'Syncthingy' application in desktop mode it will say 'Starting Syncthingy' and then close. Apparently syncthing-gtk does not have this issue: https://www.reddit.com/r/SteamDeck/comments/vocyi5/comment/j3kjczu/?utm_source=share&utm_medium=web2x&context=3

**Comment by zocker-160** [comment]
Yeah this use case is not covered in the code currently.

The application closes on starting, because the port, which syncthing uses, is already blocked (by the other syncthing instance running in the background).

Originally I did not want to support this use case as it does complicate things a lot for just very very few users, which want to have it running as a service, but given the discussion in #11 about supporting Steam Deck more easily, I think it would make sense to support it.

**Comment by zocker-160** [comment]
fixed with https://github.com/zocker-160/SyncThingy/commit/3ee12f3accb4752708498438d3bc72c0079fb0c7

**Comment by mrexodia** [comment]
Awesome, thanks a lot! I’ll give it a try ASAP
