### ISSUE TITLE
Failed to start on steam deck...

### ISSUE THREAD

**Issue by zjDrummond** [zocker-160/SyncThingy#18]
Syncthing failed to start! exit code (1)  

App throws this error when I log in to the desktop mode on my steam deck (I have start at login set), or try to launch the app myself. Problem began after following the instructions to set syncthingy as a service. Syncthing is running though. I can log into the web GUI.

**Comment by zocker-160** [comment]
I will look into it.

**Comment by zocker-160** [comment]
So I just tried it a few times and I sadly cannot reproduce it on my Steam Deck including multiple reboots and switches between Game Mode and Desktop Mode.

Service runs fine and the tray icon also works as expected.

I need to know what exactly you are doing and if you might have installed some other modifications from default (e.g. decky loader etc), otherwise I will not be able to help here.

**Comment by zocker-160** [comment]
I know it is a bit cumbersome on the Steam Deck to do, but could you try to launch SyncThingy in the terminal to see what the logging output is?

You can do that by opening `Konsole` and then type `flatpak run com.github.zocker_160.SyncThingy` (or copy from this comment). I suspect that the health check is failing for some reason.

**Comment by zocker-160** [comment]
> Could not open network socket

To me indicates that the port, which syncthing is using is actually blocked (by something else, could be anything). That then causes syncthing to exit (with code 1) and therefore the health check is also failing, which then causes the tray to close with exit (1).

So the next step would be to check if the default syncthing port (assuming you didn't change it) is not blocked.

**Comment by zocker-160** [comment]
> That's a Konsole command, right? It returns "bash: netstat: command not found"

Ah damn I forgot that it is not installed on Steam Deck by default. Ah I wish I could reproduce this issue.

Do you still have Syncthing GTK installed? It could be related and someone else with a similar issue also used it before.

**Comment by zocker-160** [comment]
Reinstalling will probably not make a difference.

But you could try something else: after switching to Desktop mode (and after the notification with the error appeared) could you try visiting this url: http://127.0.0.1:8384/rest/noauth/health

It should show status: "OK". If that is the case, please run the `flatpak run com.github.zocker_160.SyncThingy` command again (as you did above) and post the output.

I need to be sure that the endpoint is actually up and running when the check fails, because if it is not, then the check will obviously fail, but if it is, then there is a bug in my code somewhere.

**Comment by zocker-160** [comment]
ohhh now this makes a lot of sense. I can actually reproduce the issue now! Thank you!

The health check fails, because it tries to access using http, which won't work. Clicking the link using the browser does however work, because it does automatically redirect to https.

I never would have guess this

**Comment by zocker-160** [comment]
With the new version https should work, if you also change the URL to https in the settings.
