### ISSUE TITLE
Performance in Steam Deck Game Mode?

### ISSUE THREAD

**Issue by lothar-cell** [zocker-160/SyncThingy#19]
Maybe it's a stupid question, but does it affect game or SteamOS performance in any way if installed as background service?

**Comment by zocker-160** [comment]
In terms of RAM / Memory usage no, the background process uses 10 - 40 MiB depending on what it is doing, so that should not have any meaningful impact.

When files are actually being synchronized and sent over the network, for example synchronizing something like 40GB of game files, it will have an impact on performance while the sync is running. This should be expected though.

Outside of that, when it is just idling and no files are being transferred, you will not notice any difference, neither in performance nor in battery life.

**Comment by lothar-cell** [comment]
Sounds good! It's a neat software, finally I've sound a proper solution for my cross-platform file transfer needs, thank you!
