### ISSUE TITLE
Indicator tray icon invisible when autostarting Syncthingy (Manjaro, GNOME 46, X11)

### ISSUE THREAD

**Issue by P9k** [zocker-160/SyncThingy#28]
I have the strange problem that the indicator tray icon is invisible (for a lack of a better term) when Syncthingy is automatically started on login:
![2024-06-24_11-34-44_Syncthingy-Tray-Icon-1](https://github.com/zocker-160/SyncThingy/assets/10435455/375a75d6-0957-4e44-88a2-5de2efacaca5)

As far as I can tell, Syncthing itself runs fine and also the tray icon can be interacted with via right-clicking:

![2024-06-24_11-35-31_Syncthingy-Tray-Icon-2](https://github.com/zocker-160/SyncThingy/assets/10435455/cefab90c-f136-4e6e-8e62-f1bcff0366d6)

![2024-06-24-11-38-00_Syncthingy-Tray-Icon-4](https://github.com/zocker-160/SyncThingy/assets/10435455/4ada510a-5533-4daa-834a-3d33418cfa8c)

If I stop Syncthingy and restart it manually, the icon looks normal:
![2024-06-24_ 11-36-00_Syncthingy-Tray-Icon-3](https://github.com/zocker-160/SyncThingy/assets/10435455/c7891da0-bdfe-4e97-9d94-876e3914d18f)

---

Any idea what might cause this behavior?

My system runs Manjaro Linux with GNOME 46 and X11 as window manager. (Also in case it's of any relevance, I have the ["Dash to dock"](https://extensions.gnome.org/extension/307/dash-to-dock/) Gnome extension activated)

**Comment by zocker-160** [comment]
This could be a tricky one to debug. 

Based on what you are describing I would wildly guess that this could be caused by some weird race conditions where a service needs to be running before loading the tray in order to see the icon. Figuring out exactly where the issue is, will probably not be easy.

I personally would try to delay the start of SyncThingy and see if that changes anything. If yes then that would be even more evidence for my theory.

From the application's point of view there is sadly not much I can do, because for the autostart feature all I am doing is requesting the autostart entry to be generated using the xdg-desktop-portal API. Usually that creates a desktop file placed in `.config/autostart/`

**Comment by P9k** [comment]
Your recommendation worked! I have introduced  `sleep 5` before calling Syncthingy in the autostart file and now the icon appears.
