### ISSUE TITLE
Provide valid reason for running in the background

### ISSUE THREAD

**Issue by colans** [zocker-160/SyncThingy#3]
I got a pop-up saying something like:
> This application is running in the background.  There may be a valid reason, but the application has not provided one.

I chose `Allow`, but I'm assuming there's some other code that can be added so that it won't have to ask you?

Thanks for putting this together!

**Comment by zocker-160** [comment]
Thank you for pointing that out.

Yes you are right currently the application installs without background permissions, because I am not implementing the desktop portal to provide a reason to the system.

I don't think this is a big deal, however it should be easy to fix, so I am putting it on my TODO.

**Comment by zocker-160** [comment]
implemented with a91d2066eb794edb7b6c27c3ae2cca6523256bfe

It will ask for background permission on first start like this:
![Screenshot_20220818_141953](https://user-images.githubusercontent.com/36563538/185393197-40fb8f48-2a2a-47a8-952a-e3936d1d8a39.png)

it will be available once 0.4 is published on Flathub.
