### ISSUE TITLE
SyncThingy not using SyncThing configuration file

### ISSUE THREAD

**Issue by LydonThorpe** [zocker-160/SyncThingy#30]
Hello, I installed SyncThing and followed the instructions [here](https://github.com/zocker-160/SyncThingy?tab=readme-ov-file#note) to add my existing SyncThing configuration file.
![image](https://github.com/user-attachments/assets/4b35904f-6e02-4150-8857-3327da326709)

However when I start Syncthingy and open the web GUI it doesn't show any of my existing configurations settings.

I've confirmed that config file is correct, as when I run SyncThing manually from the terminal it loads correctly (using the config from that file).

Do I need to name the file something else other than the "config.xml" default that SyncThing uses?

**Comment by LydonThorpe** [comment]
Ah I figured it out, the correct location for the file is com.github.zocker_160.SyncThingy/.local/state/syncthing. 
![image](https://github.com/user-attachments/assets/c9e8f631-1ad3-444e-8357-50e4f578dc84)
Placed my SyncThing config.xml file there and it worked!

Opening a PR to update the docs.

**Comment by zocker-160** [comment]
This issue is kinda weird sadly, as you don't seem to be alone on this, but for most other users this is not the case.
![image](https://github.com/user-attachments/assets/39445116-0553-4b1c-a15c-5c003a4e6466)

I have not yet been able to figure out, what is influencing this, but on a fresh install, the location of the config is as specified in the Readme.

Unless newer versions of synthing changed this behavior.
