### ISSUE TITLE
Syncthingy not running on reboot (steam deck)

### ISSUE THREAD

**Issue by Canpake59** [zocker-160/SyncThingy#34]
I am having an issue on my steam deck with having Sync Thingy run when it boots into gaming mode. It works fine when I switch to desktop mode and then back, but not on a fresh boot into gaming mode. I followed the steps under "Install background service" but it still doesn't seem to work. Any suggestions?

EDIT: Apologies, it actually did seem to work, just took a much longer time to start than I had thought. Is there anyway to tell in gaming mode when it starts?

**Comment by zocker-160** [comment]
Sadly I have no control over when the system decides to start the background service.

To check if it is running, you can point a browser to the webui in game mode and see if it loads. 
I know it is not a great indicator, but I cannot think of a better way outside of custom plugins for the gamepad ui.

**Comment by Canpake59** [comment]
No problem, I appreciate the response.

**Comment by DJCrashdummy** [comment]
as a workaround using [Decky Loader](https://decky.xyz/) may be worth a try... it's a [plugin](https://plugins.deckbrew.xyz/) system to easily change, launch execute things in gaming mode.

there is already a Syncthing plugin for running & controlling Syncthing in gamining mode. - although it states that *Syncthing GTK* has to be installed... so i have no idea how well it plays along with *SyncThingy*!

perhaps it is also possible to write a plugin to manually start or control when to start the background services in gaming mode. 🤷

**Comment by zocker-160** [comment]
You only really need a plugin to send a ping to the service endpoint to find out if it is running or not. 

I could also offer an additional endpoint for control if that is required, but I think calling systemd for status and start / stop should be enough.

**Comment by DJCrashdummy** [comment]
i'm not an expert, but it seems that there are already open issues about this topic...
- one about supporting SyncThing without technical details: https://github.com/theCapypara/steamdeck-decky-syncthing/issues/4
- and one about supporting systemd: https://github.com/theCapypara/steamdeck-decky-syncthing/issues/18

**Comment by zocker-160** [comment]
yeah I have just seen those two issues as well, I am not exactly sure what the issue is, but I also don't know how the plugin works.

**Comment by DJCrashdummy** [comment]
perhaps at least in the one issue about supporting SyncThingy it may be worth as its developer to ask what is the exact issue and if/how you can make things easier for them.

**Comment by theCapypara** [comment]
The issue was, last time I tried, that SyncThingy keeps running even if switching from Desktop mode to Gamescope. 

Since the plugin expects to manage the Syncthing process in Gamescope things go bad. When the plugin is started Syncthingy needs to not be running anymore, so that the plugin can take over starting it and monitoring the process.

**Comment by zocker-160** [comment]
> The issue was, last time I tried, that SyncThingy keeps running even if switching from Desktop mode to Gamescope.

@theCapypara 
This is only true when the user installs it as a systemd service in which case systemd commands should be used instead.
But when the user just installs it "normally", it should behave the same SyncthingGTK.

Furthermore when installed normally (not as systemd service), then the flatpak autostart will not do anything when booting into Gamescope.

IMHO installing and managing it via systemd is the "proper" way of handling background processes. All the plugin needs to really is to call `systemd --user start | stop | status syncthing`

**Comment by theCapypara** [comment]
This is exactly what it is doing.

The problem was when I tested that Syncthingy kept running in Gamescope even without a Systemd service (when coming from Desktop mode and starting Syncthingy there). I have not investigated this further, I don't really know how this is even possible given Flatpak's design. It's been a while I checked this though.

**Comment by theCapypara** [comment]
Basically what the plugin is doing:
- When loaded it looks for a Systemd service:
  - If it is configured to use a Flatpak, it will create one
  - If its configured to use a Systemd service, it will just use that
- When autostart is enabled, it will then start the systemd service
- When switching to Desktop mode, it will stop the service, unless its configured to keep it running

What happens with Syncthingy is that when I start Syncthingy in desktop mode and switch to Gamescope, syncthing is still listening on port 8384, the Flatpak is still running in the background & the plugin fails to start the systemd service and thus the plugin refuses to work, since a lot of things in it rely on the plugin being able to start & stop Syncthing.

Since the user needs to do these steps to get Syncthing set up, this breaks everything until a reboot, which is just confusing for everyone, which is why I removed it from the list of supported Flatpaks. Nothing is stopping people from using it anyway though.

I'm not sure if this is due to the way KStatusNotifier works, I have never worked with this interface before, or because of the awful hacks Valve has implemented in handling the user session when switching modes, but I just know that "Syncthing GTK" doesn't have this behaviour.

I unfortunately can't reproduce this anymore, since I don't have SteamOS anymore.

**Comment by theCapypara** [comment]
I think the best way to solve this would be if Syncthingy also installed a polkit rule.

**Comment by zocker-160** [comment]
@theCapypara it is installed as a user service, no root needed.
https://github.com/zocker-160/SyncThingy/blob/71f217cd771133c7a85b6d2761e41e7535eb294b/src/ServiceDialog.cpp#L10

**Comment by zocker-160** [comment]
@theCapypara 
btw if there is anything I can change to make it easier for you, let me know. I am open to help you out.
