### ISSUE TITLE
"Open WebUI" options not working on Steam Deck since OS update

### ISSUE THREAD

**Issue by DrGonzo94** [zocker-160/SyncThingy#7]
Hi, unsure if SyncThingy problem or not, but here goes

I use SyncThingy on Steam Deck, and after OS update Syncthiny gives warning "Background permission revoked - SyncThingy might not work as expected!". I can't seem to remedy this via settings in SteamOS (desktop mode). Syncthing still seems to be running, but the "Open WebUI" and "SyncThingy v0.5.1" options in the System Tray menu doesn't work anymore.

**Comment by DrGonzo94** [comment]
Duplicate issue, sorry

**Comment by zocker-160** [comment]
Sorry for the late reply (was on vacation), this issue is not really duplicate, since I did the OS update today and I have exactly the same issues as you described.

The permission revoked error can be fixed by doing a full reboot. The other issue with the buttons not working does still persist though and I sadly currently have no idea why that is.

**Comment by zocker-160** [comment]
this bug seems to be related to https://github.com/ValveSoftware/SteamOS/issues/775

**Comment by zocker-160** [comment]
closing as this issue is fixed in the upcoming SteamOS 3.4 update
see https://store.steampowered.com/news/app/1675200/view/3383920059429575957
