### ISSUE TITLE
Quit triggered after settings are updated

### ISSUE THREAD

**Issue by SashaPGT** [zocker-160/SyncThingy#8]
Every time I update settings via Syncthingy Settings panel and try to exit from it, X on the top right, cancel or OK. This is what I get.

```
QSocketNotifier: Can only be used with threads started with QThread
running inside Flatpak 

Using Icon: "com.github.zocker_160.SyncThingy.white"
/app/bin/syncthing
Requesting background permission...
Background / Autostart permission granted
open settings
saving settings
running inside Flatpak 

Using Icon: "com.github.zocker_160.SyncThingy.white"
Requesting background permission...
quit triggered
```

Is there any way I can keep this running after settings are updated, without needing to start Syncthingy from the appmenu again?

**Comment by zocker-160** [comment]
Are you running a desktop environment based on GTK(4)?

If yes, then this is a known issue and I sadly have no idea what is going on or why this is happening, because on KDE everything works as it should (as in the application does not exist when pressing OK or cancel on the settings dialog).

From my testing it seems like that it works fine on older GTK3 based DEs so this is probably a bug that got introduced somewhat recently.

If this really bothers you, I can look into a workaround.

**Comment by SashaPGT** [comment]
I see, I'm running Syncthingy on Fedora 37 Beta with GNOME 43.

**Comment by zocker-160** [comment]
yeah this makes sense, I can reproduce this issue on anything newer than and including GNOME 42.

Exactly the same binary is behaving in a different way despite the same runtime and sandboxing of Flatpak. This is really strange to say the least.

**Comment by zocker-160** [comment]
alright so small update

After messing around for a few hours I finally found a very ugly workaround for this bug, but it works I guess.
