### ISSUE TITLE
Syncthingy launcher & tray icon has red dot in the center of the icon

### ISSUE THREAD

**Issue by trymeouteh** [zocker-160/SyncThingy#9]
What does this mean?

**Comment by MaximumWoahverdrive** [comment]
The syncthing icon with a red dot / glow in the center is just the logo of this program,
it bears no meaning in regards to the sync status.

**Comment by zocker-160** [comment]
It has no meaning.

I added it, because I got requests from the community to make it different than the official Syncthing icon, so ppl can distiguish between the two applications in an icon only application launcher in case they have both Syncthing and SyncThingy installed on the system.

If you have a better logo suggestion, feel free to let me know, I am really bad at this :laughing: .

**Comment by trymeouteh** [comment]
I would suggest adding another line in the circle of the logo or rotating the icon 45 degrees, 90 degrees or 180 degree to make it unique.
